feat: feature flags
aeternity/aescan pull request #1003
Opened 2024-12-05 11:46 UTC by michele-franchi

## Description

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2025-01-01 06:50 UTC, janmichek requested changes
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/5dfec4f2-9f20-4061-a3cd-51d1f6b38d04" />
There is a missing icon for the coin

2025-01-02 01:57 UTC, janmichek commented
I can also see the tests are not passing. Will you work on it? You might spin it 5 or six times if you sure its correct. The infrastructure is in poor state and cannot handle our basic e2e tests.

2025-01-09 07:46 UTC, janmichek commented
On it, still testing it ...

2025-01-13 02:48 UTC, janmichek reviewed
Overall good job, given the fact its a messy feature 🦖 
I suggested some minor naming edits to keep the consistency and also asked for explanation

2025-01-13 02:48 UTC, janmichek commented on src/components/TokensPanel.vue
> +const tokenSelectVisible = computed(() => {
```suggestion
const hasTokenSelect = computed(() => {
```

2025-01-13 02:48 UTC, janmichek commented on src/components/MenuItem.vue
> +        v-for="submenu in visibleSubmenus"
why there is 'visible', 'hidden' and 'disable'?
Maybe there is no need for disabling anymore, that would make it more readible.

2025-01-13 02:48 UTC, janmichek commented on src/components/TheNavigation.vue
> +const visibleMenuOptions = computed(() =>
I am not super-fan of mixing 'visible' and 'hidden' naming. At least not in single component .]

2025-01-13 02:48 UTC, janmichek commented on src/stores/blockchainStats.js
> +      // no stats available
then there is no need to try catch

2025-01-13 02:48 UTC, janmichek commented on src/stores/recentBlocks.js
> +      updateBlockHeight(message.payload)
can you just explain a bit here, please?

2025-01-13 02:48 UTC, janmichek commented on src/stores/transactions.js
> +      // no stats available
What is this good for when there is no sanitization in catch block?

2025-01-13 02:48 UTC, janmichek commented on src/utils/constants.js
> -export const LAEX_CONTRACT_ID = 'ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt'
So Laex is not gonna have its logo anymore?

2025-01-13 02:48 UTC, janmichek commented on src/stores/webSocket.js
> +    if (isSpecificEntityMessage && isSubscribedTransactionMessage) {
can you explan here pls? How this could work before? :D

2025-01-13 03:02 UTC, janmichek commented
... and I only checked the mainnet/testnet preview. I didn't check the HC connection to aescan ofc.

2025-01-15 13:19 UTC, michele-franchi commented on src/stores/blockchainStats.js
> +      // no stats available
Good catch, I forgot to set the default value.

2025-01-15 13:20 UTC, michele-franchi commented on src/stores/transactions.js
> +      // no stats available
Good catch, I forgot to set the default value.

2025-01-15 13:21 UTC, michele-franchi commented on src/utils/constants.js
> -export const LAEX_CONTRACT_ID = 'ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt'
This has to be reworked completely, to be able to let other projects integrate avatars and price data. I see no harm in temporarily removing it and it make no sense for hyperchains.

2025-01-15 13:30 UTC, michele-franchi commented on src/components/PriceLabel.vue
> +  props.currency || defaultCurrency.value.symbol,
Agree, I moved it to the default value of `currency` prop.

2025-01-15 13:33 UTC, michele-franchi commented on src/stores/recentBlocks.js
> +      updateBlockHeight(message.payload)
See https://github.com/aeternity/aescan/pull/1003#discussion_r1916658292

2025-01-15 13:53 UTC, michele-franchi commented on src/components/MenuItem.vue
> +        v-for="submenu in visibleSubmenus"
I removed "visibleSubmenus" computed property, it's not necessary anymore. I would keep the "disable" option as it could come handy.

2025-01-15 13:53 UTC, michele-franchi commented on src/components/TheNavigation.vue
> +const visibleMenuOptions = computed(() =>
Agree, I renamed it.

2025-01-15 15:43 UTC, michele-franchi commented
@janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.

2025-01-16 02:02 UTC, janmichek commented on src/utils/constants.js
> -export const LAEX_CONTRACT_ID = 'ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt'
Not super happy about it but ok. Please create followup issue with detailed explanation for later.

2025-01-16 02:03 UTC, janmichek commented
> @janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.

Correct, there are ongoing issues with infrastructure @mmpetarpeshev @thoughtfulcool

2025-01-16 02:17 UTC, janmichek approved these changes
Good, I approve it. If you dont have quick fix for the comments I pointed, just create followup. Its not that important, if you rush to deliver it.

2025-01-16 02:17 UTC, janmichek commented on src/components/PriceLabel.vue
> +    default: () => storeToRefs(useConfigStore()).currency.value.symbol,
That kinda exotic definition. I dont want to hold it up, we can improve it later if you don't have any idea for now. I am till not really sure how it works here.

2025-01-16 02:17 UTC, janmichek commented on src/components/TheNavigation.vue
> +        v-for="menu in menuOptionsWithSubmenus"
I personally dont use 'with' for any naming as it is telling its glueing 2 things together

2025-01-16 08:55 UTC, mmpetarpeshev commented
> > @janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.
> 
> Correct, there are ongoing issues with infrastructure @mmpetarpeshev @thoughtfulcool

@janmichek Whats the issue here ?

2025-01-16 10:38 UTC, michele-franchi commented on src/components/PriceLabel.vue
> +    default: () => storeToRefs(useConfigStore()).currency.value.symbol,
https://github.com/aeternity/aescan/issues/1033

2025-01-16 10:38 UTC, michele-franchi commented on src/components/TheNavigation.vue
> +        v-for="menu in menuOptionsWithSubmenus"
https://github.com/aeternity/aescan/issues/1033

2025-01-16 13:45 UTC, michele-franchi commented on src/utils/constants.js
> -export const LAEX_CONTRACT_ID = 'ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt'
https://github.com/aeternity/aescan/issues/1034

2025-01-16 13:45 UTC, merged

2025-01-20 01:57 UTC, janmichek commented
> > > @janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.
> > 
> > 
> > Correct, there are ongoing issues with infrastructure @mmpetarpeshev @thoughtfulcool
> 
> @janmichek Whats the issue here ?

as described by @michele-franchi

2025-01-20 06:50 UTC, mmpetarpeshev commented
> > > > @janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.
> > > 
> > > 
> > > Correct, there are ongoing issues with infrastructure @mmpetarpeshev @thoughtfulcool
> > 
> > 
> > @janmichek Whats the issue here ?
> 
> as described by @michele-franchi . We have been solving this multiple times without result

There isnt any issue with the infrastructure , please describe exactly what you see , because one test is not passing doesnt mean anything to me.

2025-01-20 08:06 UTC, janmichek commented
> > > > > @janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.
> > > > 
> > > > 
> > > > Correct, there are ongoing issues with infrastructure @mmpetarpeshev @thoughtfulcool
> > > 
> > > 
> > > @janmichek Whats the issue here ?
> > 
> > 
> > as described by @michele-franchi . We have been solving this multiple times without result
> 
> There are no issues with the infrastructure. Please describe exactly what you are observing and avoid making unsupported statements. A single failing test does not provide enough information to me to diagnose the problem. Additionally, we do not rely on your local environment to deliver software.Please describe exactly what the issue is , so I can take a look.

As described before several times we observed that the app is totally fine, e2e tests pass on localhost. On PR staging deployment tests are randomly failing. Recently I implemented test retries to avoid flaky tests. If test fails, it will retry 10 times, but didn't solve the issue. There is plenty of evidence in this or previous PR check logs


> There are no issues with the infrastructure

On Wednesday there were no servers available. Every time the staging build finished I always got 'No server available' when going to PR preview link

2025-01-20 08:24 UTC, mmpetarpeshev commented
> > > > > > @janmichek One test not passing seems to be related to the deployment, tests pass on my local environment and I can see the "Trades" tab.
> > > > > 
> > > > > 
> > > > > Correct, there are ongoing issues with infrastructure @mmpetarpeshev @thoughtfulcool
> > > > 
> > > > 
> > > > @janmichek Whats the issue here ?
> > > 
> > > 
> > > as described by @michele-franchi . We have been solving this multiple times without result
> > 
> > 
> > There are no issues with the infrastructure. Please describe exactly what you are observing and avoid making unsupported statements. A single failing test does not provide enough information to me to diagnose the problem. Additionally, we do not rely on your local environment to deliver software.Please describe exactly what the issue is , so I can take a look.
> 
> As described before several times we observed that the app is totally fine, e2e tests pass on localhost. On PR staging deployment tests are randomly failing. Recently I implemented test retries to avoid flaky tests. If test fails, it will retry 10 times, but didn't solve the issue. There is plenty of evidence in this or previous PR check logs
> 
> > There are no issues with the infrastructure
> 
> On Wednesday there were no servers available. Every time the staging build finished I always got 'No server available' when going to PR preview link

"On Wednesday there were no servers available. Every time the staging build finished I always got 'No server available' when going to PR preview link" - **means exactly that , when there are many open PR's we hitting the node capacity limit.If that happens it needs some time to free resources or you can ping me to do it manually. 
About the tests we saw that cant be infra related as the service is available , but next time ping me on chat , so we can take a look again.**

2025-01-20 08:47 UTC, janmichek commented
@mmpetarpeshev here is another example, you can take a look again https://github.com/aeternity/aescan/actions/runs/12762629388/job/35850498519?pr=993

2025-01-20 14:02 UTC, mmpetarpeshev commented
> @mmpetarpeshev here is another example, you can take a look again https://github.com/aeternity/aescan/actions/runs/12762629388/job/35850498519?pr=993

Yeah , nothing that make sense to infra level :
Error: The operation was canceled. Do you know what this means in context of cypress ? 
Lets we discuss that in slack , it will be easier.