fix: Remove workaround of total token supply
aeternity/aescan pull request #268
Opened 2023-05-30 08:43 UTC by janmichek

## Description
resolves #37 

## Demo
MDW provides slightly different amount, but I guess it's more accurate than AEknow
![image](https://github.com/aeternity/aescan/assets/15363559/ea712270-0ffb-4709-8c8b-5df723e16c71)

## Checklist:
- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] Use fixed value from MDW

2023-05-30 09:05 UTC, michele-franchi requested changes
We cannot "guess" if the values is correct, it should be verified. If you look at the inflation curve the current value should be around "415017440". Could you please check and verify with mdw why there's a difference?

2023-05-30 09:26 UTC, janmichek commented
> We cannot "guess" if the values is correct, it should be verified. If you look at the inflation curve the current value should be around "415017440". Could you please check and verify with mdw why there's a difference?

I mean, I would better rely on our solution then third party unknown formu. Question raised here https://github.com/aeternity/ae_mdw/pull/1252#issuecomment-1568098872

2023-05-31 08:57 UTC, lukeromanowicz reviewed
The code looks good to me but I'm not able to verify if the new value is correct

2023-05-31 08:59 UTC, janmichek commented
@michele-franchi Something is being discussed .) https://github.com/aeternity/ae_mdw/pull/1252#issuecomment-1568922984

2023-06-05 06:30 UTC, michele-franchi requested changes
<img width="537" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/3655ce16-3bc3-4228-9891-7e89712c20b6">

Distribution should also include the burned amount, could you please adjust it?

2023-06-05 10:43 UTC, janmichek commented
> <img alt="image" width="537" src="https://user-images.githubusercontent.com/11598532/243269712-3655ce16-3bc3-4228-9891-7e89712c20b6.png">
> 
> Distribution should also include the burned amount, could you please adjust it?

Good catch, ser. Fixed.

2023-06-06 07:59 UTC, lukeromanowicz approved these changes
Apart from one small issue, it looks good to me. I'm approving in advance

2023-06-06 08:35 UTC, janmichek commented on src/stores/marketStats.js
> +    console.log('distribution.value', distribution.value)
Ooops, thanks for second eyes. Removed

2023-06-06 09:17 UTC, michele-franchi approved these changes
Looks good 👏

2023-06-06 09:24 UTC, CharisSiarampalis approved these changes

2023-06-06 12:06 UTC, merged