feat: dashboard hints
aeternity/aescan pull request #319
Opened 2023-06-15 07:09 UTC by lukeromanowicz

## Description
Resolves #180 
Implements remaining dashboard hints except transactions table (as agreed with @michele-franchi)

## Demo
![image](https://github.com/aeternity/aescan/assets/46789227/e47f786a-b871-41b3-b163-b1ad17e9b573)
![image](https://github.com/aeternity/aescan/assets/46789227/0bb830f8-4164-477d-ba0a-7d327aead81d)

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change does not require a change to the documentation.

2023-06-15 07:39 UTC, janmichek requested changes
Good job, ser! Please consider my suggestions.

One more thing from the previous PR

In state channels hints, there should be also explained responder in:

`participants: 'Initiator is the account that created the State Channel via ChannelCreateTx.',`
Could you improve it as well?

2023-06-15 07:39 UTC, janmichek commented on src/utils/hints/namesHints.js
> +  recentlyActivatedData: 'The Name and its owner who recently activated it. Depending on the length a Name is activated either through an auction or by direct acquisition.',
Here I would explain precisely how it works (13 characters threshold). Personally I would use some simpler word than acquisition

2023-06-15 07:39 UTC, janmichek commented on src/utils/hints/namesHints.js
> +  activationPrice: 'Amount of AE tokens than have been burned during Name activation.',
```suggestion
  activationPrice: 'Amount of AE tokens paid for the Name activation.',
```

Is it really 'burned' ?

2023-06-15 07:42 UTC, janmichek commented
How about hints in here? Should it be part of this PR?
![image](https://github.com/aeternity/aescan/assets/15363559/b5d2f14a-db86-4be6-9ad5-7de6721695fe)

2023-06-15 10:56 UTC, lukeromanowicz commented on src/utils/hints/namesHints.js
> +  activationPrice: 'Amount of AE tokens than have been burned during Name activation.',
Isn't it burned? :O

2023-06-15 10:58 UTC, lukeromanowicz commented on src/utils/hints/stateChannelsHints.js
> +  initiator: 'Initiator is the account that created the State Channel via ChannelCreateTx.',
I'll update it to use the version we agreed upon in state channel details hints PR

2023-06-15 10:59 UTC, lukeromanowicz commented
@janmichek thanks for your suggestion. The transactions section is skipped until they are implemented in another task. If by the time this task is mergable they will be still in development - I'll create an appropriate task to implement them. Otherwise I will add them before merging

2023-06-15 11:01 UTC, janmichek approved these changes
Cool, thanks for fixes ✌️

2023-06-16 07:25 UTC, CharisSiarampalis approved these changes

2023-06-19 09:49 UTC, michele-franchi approved these changes
Looks good!

2023-06-19 09:49 UTC, merged