feat: keyblock and microblock links
aeternity/aescan pull request #380
Opened 2023-07-18 10:40 UTC by lukeromanowicz

## Description
Resolves #366 
Implements clickable keyblock and microblock hashes/block heights

## Demo
![image](https://github.com/aeternity/aescan/assets/46789227/c12cdda0-758e-427b-b839-6282721df2a6)

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] My change does not require a change to the documentation.

2023-07-18 10:43 UTC, lukeromanowicz commented on src/components/ContractsTable.vue
> +          Created
Unrelated, I changed it from "Created By" back to "Created" because on current develop "Created By" header is duplicated in two columns.

2023-07-18 10:43 UTC, lukeromanowicz commented on src/utils/adapters.js
> +    expiration: DateTime.fromMillis(oracle.approximate_expire_time),
Unrelated: fix for some regression introduced in previously merged PRs

2023-07-18 13:39 UTC, CharisSiarampalis approved these changes

2023-07-19 11:22 UTC, janmichek approved these changes
Looks great, ser! 🚀 

I am giving 2 suggestions to consider

1) Is it right to have both routes to keyblock detail? `/keyblocks/kh_2a9D6kQcWAtK6AzLAivi38BeFbcVUF4Tcp25RPvrWqNoUoQWHj` and `/keyblocks/801118` ? Shouldn't this be translated somehow to just one?
In previous explorer was defined with just sequenced number.
There is param `keyblockHash` is keyblocksDetailsStore, which sometimes is not a hash.

2) So there is no link to the currently mined keyblock. Wouldn't be more explainable UX to redirect to the currently mined keyblock detail with the corresponding message on it?

2023-07-19 11:29 UTC, lukeromanowicz commented
Thanks for the review, @janmichek. To answer your points:

1. It can be easily done. I followed my guts to support both similarly to the API, but we can do the redirects to use keyblock hash. @michele-franchi please define which behavior should be implemented here
2.  Not sure if I understand correctly. Can you, please, mark on a screenshot what part of the UI you are referring to?

2023-07-19 11:47 UTC, janmichek commented
> 2\. Not sure if I understand correctly. Can you, please, mark on a screenshot what part of the UI you are referring to?

I was not precise with the description. The thing I propose is to make all links to keyblock detail active. In the case of future ones, just display 'This keyblock has not been mined yet.'

2023-07-19 11:52 UTC, lukeromanowicz commented
Oh, interesting idea. I like it :+1: @michele-franchi do you approve? If you do, should I use the same design as for the accounts that don't have any activity yet?

2023-07-20 09:28 UTC, michele-franchi commented
> Looks great, ser! 🚀
> 
> I am giving 2 suggestions to consider
> 
> 1. Is it right to have both routes to keyblock detail? `/keyblocks/kh_2a9D6kQcWAtK6AzLAivi38BeFbcVUF4Tcp25RPvrWqNoUoQWHj` and `/keyblocks/801118` ? Shouldn't this be translated somehow to just one?
>    In previous explorer was defined with just sequenced number.
>    There is param `keyblockHash` is keyblocksDetailsStore, which sometimes is not a hash.
> 2. So there is no link to the currently mined keyblock. Wouldn't be more explainable UX to redirect to the currently mined keyblock detail with the corresponding message on it?

1. If it's possible to always use the keyblock sequence than we could to that but I don't see any issue with using both of them, it could be handy. If it's an issue we could start with the sequence and add also hash support later.
The only thing that comes to my mind is that we would have to fetch the keyblock height in the search bar if someone enters the hash.

2. Yes, that would be great. We could use the message we already have with the account.

2023-07-20 10:07 UTC, janmichek commented
1. if we plan to use the solution for both identifiers, then the param name `keyblockHash` is not correct

2023-07-20 13:14 UTC, michele-franchi requested changes
Looks good but some parts are missing:

<img width="654" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/c63da6ce-7b02-48ac-99c3-0e572264559c">

<img width="1368" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/828947b3-ba99-4877-ad69-d04daa4eea3b">

<img width="1386" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/c2fccefa-000d-4e03-845b-22857b766384">

<img width="1317" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/61ec8538-e82a-4140-a6ad-b55f047f17f0">

<img width="1401" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/1a24b29b-5cf0-4322-9a0a-8c9452fc2bf4">

Could you please adjust them? Also please have a look at my comment above.

2023-07-20 13:15 UTC, janmichek commented
@michele-franchi That's the future ones I was mentioning above

2023-07-20 14:41 UTC, lukeromanowicz commented
@michele-franchi as stated in the description it was correct and expected up until our most recent discussion. I implemented the support for non-minted keyblocks so from now on all keyblock heights should be covered.

@CharisSiarampalis I did a lot of changes - could you, please, help us out, please, to make sure all block heights are links now (even those which are not minted yet)

2023-07-21 08:29 UTC, CharisSiarampalis commented
@lukeromanowicz Keyblock height is not clickable on mobile. Is this normal?

![image](https://github.com/aeternity/aescan/assets/42606212/bbf43823-d062-486f-9e93-b04a99d8051f)

2023-07-21 08:37 UTC, lukeromanowicz commented
@CharisSiarampalis it wasn't. Thanks for reporting - fixed

2023-07-21 09:36 UTC, CharisSiarampalis approved these changes

2023-07-24 06:23 UTC, michele-franchi approved these changes
Good job 👏

2023-07-24 07:51 UTC, merged