Nft details inventory tab
aeternity/aescan pull request #487
Opened 2023-08-29 13:52 UTC by janmichek

## Description
resolves #146 

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-09-05 12:57 UTC, janmichek commented on src/components/NftsDetailsPanel.vue
> +  <app-panel class="nfts-details-panel">
refactor naming according to convention, made a mistake before

2023-09-05 13:00 UTC, janmichek commented on src/components/NftsPanel.vue
> +  await fetchNfts({ queryParameters: `/v2/aex141?limit=${limit.value}` })
also fix from previous part

2023-09-05 13:01 UTC, janmichek commented on src/components/NftsTemplatesOwnersTableCondensed.vue
> +    font-family: var(--font-primary);
header and data needed to be overstyled as they are tables within table cell. It inherited styles

2023-09-07 06:34 UTC, michele-franchi commented
@janmichek Could you align this PR to develop?

2023-09-07 08:05 UTC, janmichek commented
> @janmichek Could you align this PR to develop?

rebased

2023-09-11 06:25 UTC, michele-franchi commented
Needs to be rebased again after the recent merges @janmichek

2023-09-11 10:11 UTC, janmichek commented
@lukeromanowicz @michele-franchi all fixed, you can review now

2023-09-11 12:06 UTC, lukeromanowicz requested changes
Very very nice job. Close to perfect. Very impressing :sunglasses:

2023-09-11 12:06 UTC, lukeromanowicz commented on src/components/NftsTransfersPanel.vue
> +import { isDesktop } from '~/utils/screen'
weird import

2023-09-11 12:06 UTC, lukeromanowicz commented on src/components/NftsTransfersPanel.vue
> +import { computed } from 'vue'
Computed doesn't need to be imported. It's built in

2023-09-11 12:06 UTC, lukeromanowicz commented on src/pages/nfts/[id].vue
> +import NftDetailsPanel from '~/components/NftsDetailsPanel'
wrong import alias

2023-09-11 12:35 UTC, janmichek commented
> Very very nice job. Close to perfect. Very impressing 😎

Thanks for the great suggestions. Fixed

2023-09-11 15:52 UTC, lukeromanowicz approved these changes
Very nice, well done :rocket:

2023-09-12 07:54 UTC, michele-franchi approved these changes
Good job! I left two minor suggestions, please have a look at it.

2023-09-12 07:55 UTC, janmichek commented on src/utils/hints/nftHints.js
> +  inventorySupply: 'The number of NFTs that are minted from this template.',
accepted

2023-09-12 07:55 UTC, janmichek commented on src/utils/hints/nftHints.js
> +  inventoryLimit: 'The maximum number of NFTs that can be minted from this template.',
accepted

2023-09-12 07:58 UTC, merged