feat: link to token page for AEX-X classified tokens
aeternity/aescan pull request #513
Opened 2023-09-19 12:02 UTC by janmichek

## Description
resolves #435

## Demo

https://github.com/aeternity/aescan/assets/15363559/59084af4-fca3-4346-9d1a-31d996e0b869

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add token link to smart contract detail

2023-09-19 12:03 UTC, janmichek commented on src/components/ContractDetailsPanel.vue
> +        size="sm">
unrelated fix

2023-09-19 12:49 UTC, janmichek commented on src/pages/nfts/[id].vue
> +try {
Unrelated fix. I found that direct URL access to NFT detail page will cause infinite loading.
EG: https://aescan.dev.aepps.com/nfts/ct_2iJ5RHF2MbriceSetNiKARVii76Fr8Fi5wGY6kUHUj3wq7f3io
Could you help me to verify the solution @lukeromanowicz ?

2023-09-20 08:34 UTC, michele-franchi requested changes
I see some visual differences compared to other rows:
<img width="1250" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/44ffd16d-fa2d-4f55-adac-ef48a311ed99">

- There's a bigger vertical padding
- There's a right margin after the token name

Would it be possible to achieve the same row height of the other rows? Looks like we already to that for API Links?

2023-09-20 08:34 UTC, michele-franchi commented on src/components/ContractDetailsPanel.vue
> +
```suggestion
```

2023-09-20 08:55 UTC, janmichek commented on src/components/ContractDetailsPanel.vue
> +
oops forgot that. Fixed

2023-09-20 08:55 UTC, janmichek commented
> I see some visual differences compared to other rows: <img alt="image" width="1250" src="https://user-images.githubusercontent.com/11598532/269218863-44ffd16d-fa2d-4f55-adac-ef48a311ed99.png">
> 
>     * There's a bigger vertical padding
> 
>     * There's a right margin after the token name
> 
> 
> Would it be possible to achieve the same row height of the other rows? Looks like we already to that for API Links?

Thanks for second eyes. Fixed

2023-09-20 09:17 UTC, michele-franchi approved these changes
Looks good, there's another one small issue but I approve in advance.

The entire td is clickable:
<img width="1286" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/4840d2e7-ef70-4ccb-a163-191a4546c2ba">
but ideally only the symbol and text part should be, could you adjust it?

2023-09-20 09:27 UTC, janmichek commented
Thanks fixed

> Looks good, there's another one small issue but I approve in advance.
> 
> The entire td is clickable (because of flex): <img alt="image" width="1286" src="https://user-images.githubusercontent.com/11598532/269233203-4840d2e7-ef70-4ccb-a163-191a4546c2ba.png"> but ideally only the symbol and text part should be, could you adjust it?

2023-09-20 14:40 UTC, Liubov-crypto approved these changes
LGTM

2023-09-21 07:04 UTC, lukeromanowicz approved these changes
Looks good :+1:

2023-09-21 07:17 UTC, janmichek commented on src/pages/nfts/[id].vue
> +try {
Thanks, I created the followup issue. Can you provide some hint how to improve it there? https://github.com/aeternity/aescan/issues/517 I am bit out of ideas. The 'correct' approach does not work when accessed directly. This solution it's not that effective but at least works

2023-09-21 07:17 UTC, merged