feat: Implement oracles filtering
aeternity/aescan pull request #520
Opened 2023-09-21 13:35 UTC by janmichek

## Description
resolves #160 

## Demo

https://github.com/aeternity/aescan/assets/15363559/e0f4965e-ffdb-4191-b2ac-c41740fac43b

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add oracle filtering

2023-09-21 13:40 UTC, janmichek commented on src/components/TransactionsPanel.vue
> +async function loadTransactions() {
Unrelated to issue. consistency fixes in this file

2023-09-21 15:04 UTC, Liubov-crypto reviewed
Filtering is working good. 

But I have a question: It seems to me that order is broken here, correct me if I'm wrong: 
https://github.com/aeternity/aescan/assets/69896204/9de12a19-3dab-4ecc-99be-0ecc80647606

or it is sorted by Expiration date and not by Registered? or sorting by the date isn't implemented yet?

2023-09-22 09:42 UTC, Liubov-crypto commented
LGTM

2023-09-22 09:50 UTC, lukeromanowicz approved these changes
Looks and works really nice. Well done @janmichek :rocket:

2023-10-05 08:53 UTC, michele-franchi requested changes
There seems to be an issue with history / navigation.
If you navigate to the oracles page and select "Inactive" in the filter and then go back you are redirected to "/oracles?state=active" and if you go back again you are redirected to "/oracles".

Could you check it?

2023-10-11 08:47 UTC, janmichek commented
> There seems to be an issue with history / navigation. If you navigate to the oracles page and select "Inactive" in the filter and then go back you are redirected to "/oracles?state=active" and if you go back again you are redirected to "/oracles".
> 
> Could you check it?

Fixed

2023-10-11 11:36 UTC, Liubov-crypto approved these changes
Fixed, LGTM

2023-10-17 09:28 UTC, michele-franchi approved these changes
Good job

2023-10-17 09:29 UTC, merged