fix: fix routing after upgrade
aeternity/aescan pull request #561
Opened 2023-10-31 12:04 UTC by janmichek

## Description
After the infrastructure upgrade and following fixes, I discovered one more regression

## Demo

## Checklist:
- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] fix routing after upgrade

2023-10-31 12:06 UTC, janmichek commented on src/components/OraclesPanel.vue
> -import OraclesTableCondensed from '@/components/OraclesTableCondensed'
Apparently after the upgrade the imports that can be auto-imported are removed by linter. Which is a good thing

2023-10-31 15:20 UTC, Liubov-crypto reviewed
It seems that there is some issue with displaying Names in Auction - they are not visible and they become visible if I'm opening console to see issues: 

https://github.com/aeternity/aescan/assets/69896204/0c9882c9-c11f-4892-a4ad-cf2c2f8f2607


https://github.com/aeternity/aescan/assets/69896204/db4fe4b8-2372-4d93-9474-4b2a389af775

@janmichek please check it.

2023-11-01 08:58 UTC, janmichek commented
> It seems that there is some issue with displaying Names in Auction - they are not visible and they become visible if I'm opening console to see issues:
> 2023-10-31.5.11.00.mov
> 2023-10-31.5.14.25.mov
> 
> @janmichek please check it.

You are right, fixed

2023-11-01 11:43 UTC, Liubov-crypto approved these changes
Fixed, LGTM

2023-11-02 09:36 UTC, michele-franchi requested changes
It breaks the current view when you select again the active value:


https://github.com/aeternity/aescan/assets/11598532/9a444e06-f6c7-4e3c-b8f7-04a0cee149bc



Could you have a look at it?

2023-11-02 09:52 UTC, janmichek commented
> It breaks the current view when you select again the active value:
> filters.mov
> 
> Could you have a look at it?

My bad, sorry. Fixed

2023-11-02 14:34 UTC, Liubov-crypto commented
> https://pr-561-aescan.stg.aepps.com

Reproducible on Accounts page:

https://github.com/aeternity/aescan/assets/69896204/89bb1add-9e34-41b5-b1ed-ebf41719acd4

2023-11-02 15:16 UTC, janmichek commented
> > https://pr-561-aescan.stg.aepps.com
> 
> Reproducible on Accounts page:
> 2023-11-02.4.29.42.mov

Found out it was an issue even before. It was present on main deployment as well. I solved it in a different approach - reused from other selects. The selected option is hidden from select options, so this cannot even happen.

2023-11-02 16:14 UTC, Liubov-crypto commented
> https://pr-561-aescan.stg.aepps.com



> > > https://pr-561-aescan.stg.aepps.com
> > 
> > 
> > Reproducible on Accounts page:
> > 2023-11-02.4.29.42.mov
> 
> Found out it was an issue even before. It was present on main deployment as well. I solved it in a different approach - reused from other selects. The selected option is hidden from select options, so this cannot even happen.

Fixed, LGTM.

2023-11-06 07:20 UTC, michele-franchi approved these changes
Looks good to me

2023-11-06 07:21 UTC, merged