feat: translate known addresses
aeternity/aescan pull request #573
Opened 2023-11-14 10:14 UTC by janmichek

## Description
resolves #451 

## Demo

## Checklist:
- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] show translated addresses

2023-11-16 13:58 UTC, michele-franchi approved these changes
Looks good, we could also display it in the account detail but it's already a good starting point.

2023-11-16 13:58 UTC, michele-franchi commented on src/utils/constants.js
> +  { hash: 'ak_6sssiKcg7AywyJkfSdHz52RbDUq5cZe4V4hcvghXnrPz4H4Qg', name: 'Gateio' },
```suggestion
  { hash: 'ak_6sssiKcg7AywyJkfSdHz52RbDUq5cZe4V4hcvghXnrPz4H4Qg', name: 'Gate.io' },
```

2023-11-16 16:42 UTC, janmichek commented
> Looks good, we could also display it in the account detail but it's already a good starting point.

incorporated to account detail. Hope that's how you imagined it .)

2023-11-16 17:33 UTC, janmichek commented on src/components/AccountDetailsPanel.vue
> +        :label="formatKnownAddress(accountDetails.id)"
I touched this and noticed the usage of styling classes for the different views, which I recently replaced. Here was forgotten, so I adjusted it also in sibling files

2023-11-17 12:04 UTC, Liubov-crypto approved these changes
LGTM

2023-11-22 10:43 UTC, michele-franchi requested changes
It looks good but I would not apply it in the account detail like this, I have some other ideas on how to do it and I'll open a followup.
Please remove the `AccountDetailsPanel` implementation and I'll approve.

2023-11-22 12:28 UTC, janmichek commented
> It looks good but I would not apply it in the account detail like this, I have some other ideas on how to do it and I'll open a followup. Please remove the `AccountDetailsPanel` implementation and I'll approve.

Removed

2023-11-23 09:22 UTC, michele-franchi approved these changes
Good job

2023-11-23 11:13 UTC, merged