feat: New menu structure
aeternity/aescan pull request #627
Opened 2023-12-19 09:52 UTC by janmichek

## Description
resolves #617

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.

2023-12-21 13:18 UTC, janmichek commented
@michele-franchi I would like to ask you to evaluate the progress from a product/user perspective. No need to look at code now

2023-12-21 14:24 UTC, michele-franchi commented
@janmichek
The base looks good but I would adjust the following:
- Blockchain menu should also contain "State Channels" and "Hyperchains" (grey color with coming soon)
- Font size should be 16px, I see it's currently 20px which feels too big
- I would add the usual dropdown menu icon to indicate its presence:
Close state:
<img width="52" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/4192b4b0-8115-4f3f-93d5-a145dafa4d1f">

Open state:
<img width="41" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/5ba8506c-c7b4-47e3-a036-6709a589eca1">
And also applied to the mobile version of the menu, for example:
<img width="731" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/0ee7939f-4bf9-475b-8cdd-94fe5b65d19d">

2023-12-21 18:38 UTC, janmichek commented
> Blockchain menu should also contain "State Channels" and "Hyperchains" (grey color with coming soon)

Yess, State changes are missing. Will add it. Regarding to 'comming soon'. THe functionality is preserved from previous state (tooltip on hover) I can redo it into text one if you wish so


> Font size should be 16px, I see it's currently 20px which feels too big

I decided to enlarge it as now we have more room. For desktop I am fine to change it into smaller. For mobile devices I suggest to keep it larger for the comfort of tapping on it.


> I would add the usual dropdown menu icon to indicate its presence:

Agree, will add those carets. It was on my mind, but didn't want to introduce it without consultation. Now it's clear.

2024-01-08 16:43 UTC, Liubov-crypto requested changes
https://github.com/aeternity/aescan/assets/69896204/cbd64471-68d5-4e4d-af0f-413490c6b9ff

2024-01-09 01:32 UTC, janmichek commented
> 1. In Blockchain menu are still missing State Channels and Hyperchains tabs.
> 
>     2. If I'm making active AEX9 Tokens tab then Top Accounts tab will be also active (red) witch is not correct. Reproducible on mobile and web:
>        https://github.com/aeternity/aescan/assets/69896204/51c8c375-1f83-405d-b8bd-7e61f480cd84
> 
> 
> @janmichek please check it.

Thank you! fixed

2024-01-09 10:39 UTC, Liubov-crypto approved these changes
Fixed, LGTM. 

I have one question: I see that there is no option to close drop down menu to click on it. I have to open new drop down to close previous one. Reproducible on mobile and web. @janmichek  Is it correct behaviour? 


https://github.com/aeternity/aescan/assets/69896204/db86a938-6b7a-40d0-9463-e3c202dfdb41

2024-01-09 12:02 UTC, janmichek commented
> Fixed, LGTM.
> 
> I have one question: I see that there is no option to close drop down menu to click on it. I have to open new drop down to close previous one. Reproducible on mobile and web. @janmichek Is it correct behaviour?
> 2024-01-09.12.36.15.mov

I would leave it for now. On the desktop it opens on hover, so I wouldn't personally have idea of closing it by clicking

2024-01-11 09:31 UTC, michele-franchi requested changes
I suggested some UI changes which in my opinion makes the menu look even better. 

I found some issues:
- If you switch to mobile menu on Desktop items open just with hover and not with click which becomes pretty unusable:

https://github.com/aeternity/aescan/assets/11598532/00b37150-eda3-494f-8ee3-30f0161ec472
- If on Desktop you switch on Mobile, open the menu and switch again to desktop view you will get the following:
<img width="1461" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/2f8b432f-838d-4532-920b-0d608c8fac7e">

2024-01-11 09:41 UTC, janmichek commented
Thanks for your collaboration. Will adjust

2024-01-12 04:06 UTC, janmichek commented
All fixed

2024-01-19 09:15 UTC, michele-franchi requested changes
- Desktop dropdown menus do not open with hover.
- Mobile dropdown does not close when clicking again.

2024-01-22 06:51 UTC, janmichek commented
> * Desktop dropdown menus do not open with hover.
> 
>     * Mobile dropdown does not close when clicking again.

Thanks for the feedback. Not sure where I made a mistake.

2024-01-22 06:52 UTC, janmichek commented on src/components/TheNavigation.vue
> +  isDesktopResolution.value = isDesktop()
Will follow up with this
https://github.com/aeternity/aescan/issues/105
We will reuse it here and also another places

2024-01-22 06:54 UTC, janmichek commented
@Liubov-crypto please better check again, I made more changes

2024-01-22 06:57 UTC, janmichek commented
@michele-franchi I am not super-satisfied with your latest suggestion about this

![image](https://github.com/aeternity/aescan/assets/15363559/d358b4c6-80dd-4041-ab26-5434de56e6cc)

In my opinion, there should be a more visually distinguished hierarchy of different menu levels.

2024-01-22 15:07 UTC, Liubov-crypto approved these changes
LGTM

2024-02-14 09:46 UTC, michele-franchi approved these changes
I added some more suggestions, can be merged once fixed 🚀

2024-02-14 09:46 UTC, michele-franchi commented on src/components/TheNavigation.vue
> +      name: 'Contract Verification',
```suggestion
      name: 'Smart Contract Verification',
```

2024-02-14 09:46 UTC, michele-franchi commented on src/components/TheNavigation.vue
> +    },
```suggestion
```

I would remove it for now

2024-02-14 09:46 UTC, michele-franchi commented on src/components/TheNavigation.vue
> +},
```suggestion
```

I would remove it for now.

2024-02-14 09:46 UTC, michele-franchi commented on src/components/MenuItem.vue
> +    padding: var(--space-0) var(--space-3);
```suggestion
    padding: var(--space-0) var(--space-3) var(--space-0) var(--space-4);
```

I would go this way so this also solves the mobile issue where items appear at the same level:
<img width="839" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/4c01382f-edee-4181-b911-f26dc5462da0">

2024-02-15 01:22 UTC, merged