feat: Add dedicated columns to name tables
aeternity/aescan pull request #631
Opened 2023-12-20 13:53 UTC by janmichek

## Description
resolves #404

## Demo

https://github.com/aeternity/aescan/assets/15363559/294b2b88-0ea4-4508-a25f-799878d477f1

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] Add dedicated columns to name tables

2024-01-11 10:03 UTC, michele-franchi reviewed
@janmichek Buyer, Highest Bid and Last Buyer columns should be separated but time and block should be one column as the other tables.

2024-01-12 04:54 UTC, janmichek commented
> @janmichek Buyer, Highest Bid and Last Buyer columns should be separated but time and block should be one column as the other tables.

I tried to split the columns you mentioned, but also left the time-related columns as one line cell. SO everything is on one line. Coul you check, I think this would work

2024-01-15 13:58 UTC, Liubov-crypto reviewed
Should be Expired block or Expired Height? 

![exp](https://github.com/aeternity/aescan/assets/69896204/e019e938-875f-4aff-8536-e705e795f754)

the rest LGTM

2024-01-19 09:16 UTC, michele-franchi requested changes
As discussed, to be consistent with other tables, height and time columns should not be separate.

2024-01-22 09:09 UTC, janmichek commented on src/components/KeyblockDetailsPanel.vue
> -  &__keyblock-link--disabled {
unrelated cleanup

2024-01-22 09:10 UTC, janmichek commented
> Should be Expired block or Expired Height?
> 
> ![exp](https://private-user-images.githubusercontent.com/69896204/296282317-e019e938-875f-4aff-8536-e705e795f754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTQ4NzYsIm5iZiI6MTcwNTkxNDU3NiwicGF0aCI6Ii82OTg5NjIwNC8yOTYyODIzMTctZTAxOWU5MzgtODc1Zi00YWZmLTg1MzYtZTcwNWU3OTVmNzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YzI5M2RiMzhhODQ3OWZjOWUxNDJiZDBiZDk0NDEyYThmOWYyZmUxMzczNWU5NzU2NmQ0MGEyM2Q3ZmQ2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CvtfA7PwYZKfHrQVXh9Z9j5TvS3HG1Dz3QM1zkZEFro)
> 
> the rest LGTM

Thanks, I reverted the change

2024-01-22 09:11 UTC, janmichek commented
> As discussed, to be consistent with other tables, height and time columns should not be separate.

Reverted. I was curious how it's gonna feel like on line. At least we know that it could fit .)

2024-01-22 09:21 UTC, michele-franchi approved these changes
Two hints are inverted but other than that it looks good.

2024-01-22 09:21 UTC, michele-franchi commented on src/utils/hints/namesHints.js
> +  highestBidder: 'Highest bid price. Required minimum bid increase is 5%.',
```suggestion
  highestBid: 'Highest bid price. Required minimum bid increase is 5%.',
  highestBidder: 'Account of the highest bidder.',
```

2024-01-22 09:35 UTC, janmichek commented on src/utils/hints/namesHints.js
> +  highestBidder: 'Highest bid price. Required minimum bid increase is 5%.',
Thanks for the suggestion. Accepted

2024-01-22 14:39 UTC, merged