Names charts
aeternity/aescan pull request #641
Opened 2024-01-03 14:47 UTC by janmichek

## Description
resolves #533

## Demo

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add names chart

2024-01-03 15:20 UTC, Liubov-crypto requested changes
In general LGTM. 
But is this correct aligning? 
https://github.com/aeternity/aescan/assets/69896204/5f3f322c-0e4a-4b76-bdec-79966d3488ab

2024-01-04 12:50 UTC, janmichek commented
> In general LGTM. But is this correct aligning? https://github.com/aeternity/aescan/assets/69896204/5f3f322c-0e4a-4b76-bdec-79966d3488ab

Yeah, that's what is the data. I can do better with printing the labels for Y axis. There should be only full numbers, no fractions.

2024-01-08 03:59 UTC, janmichek commented
At least I fixed it in this fashion
![image](https://github.com/aeternity/aescan/assets/15363559/13280f3d-2747-4089-a864-7e8236fd536d)
Not super satisfied about it, but that's the data we get. We can consult if you guys have some bright ideas .)

2024-01-08 16:04 UTC, Liubov-crypto commented
I found that for some dates it will not shown any data, just red dot: 
![tr](https://github.com/aeternity/aescan/assets/69896204/9a354a87-146d-469d-9521-cd9f8aec8e6f)

https://github.com/aeternity/aescan/assets/69896204/83def734-9fa9-4017-8840-2c86160b7ee5

@janmichek please check it

2024-01-09 02:19 UTC, janmichek commented
> I found that for some dates it will not shown any data, just red dot: ![tr](https://private-user-images.githubusercontent.com/69896204/294961234-9a354a87-146d-469d-9521-cd9f8aec8e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjQ0NTIsIm5iZiI6MTcwNDc2NDE1MiwicGF0aCI6Ii82OTg5NjIwNC8yOTQ5NjEyMzQtOWEzNTRhODctMTQ2ZC00NjlkLTk1MjEtY2Q5ZjhhZWM4ZTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAxMzU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTMzMmI2OGRlZTUxM2YxYjMyYTc5YzgyMDk2NTAzMGVmZjZmMzU1ZDk4MGZlNmJmNjRiM2QyY2NlZWE1YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3aHKLloBzAPh4QN21ApJ4weHzYUVNoMLS2ed8nyU0jo)
> 2024-01-08.6.00.55.mov
> 
> @janmichek please check it

Good catch, fixed it.

2024-01-09 11:21 UTC, Liubov-crypto approved these changes
Fixed, LGTM.

2024-01-10 08:38 UTC, michele-franchi approved these changes
Please remove some dev lines and it will look good!

2024-01-10 08:38 UTC, michele-franchi commented on src/stores/names.js
> +  // }
Is this commented function useful or can it be removed?

2024-01-10 08:38 UTC, michele-franchi commented on src/stores/oracleDetails.js
> +    console.log('1 rawOracle.value', rawOracle.value)
```suggestion
```

2024-01-10 08:38 UTC, michele-franchi commented on src/stores/oracleDetails.js
> +    console.log('3 lastExtendedTx.value', lastExtendedTx.value)
```suggestion
```

2024-01-10 08:38 UTC, michele-franchi commented on src/stores/oracleDetails.js
> +    console.log('2 rawEvents.value', rawEvents.value)
```suggestion
```

2024-01-10 09:11 UTC, merged