feat: Warning about MDW out of sync
aeternity/aescan pull request #684
Opened 2024-03-18 08:07 UTC by janmichek

## Description
resolves #605

## Demo
![image](https://github.com/aeternity/aescan/assets/15363559/467a5f8a-0c0e-47d8-bb17-19da8ad7a422)

![image](https://github.com/aeternity/aescan/assets/15363559/5ad682e0-9767-4783-98ce-e398b2583000)

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] add syncing warning UI

2024-03-18 15:31 UTC, Liubov-crypto requested changes
I got periodically 404 errors in FF, Chrome and Safari browsers. 

Also I got these issues: 

https://github.com/aeternity/aescan/assets/69896204/1ee87688-3dba-4733-8425-b0ba2337ac91

![errr1](https://github.com/aeternity/aescan/assets/69896204/a6d0c983-a16c-4274-9d01-2822785ea518)
![cons](https://github.com/aeternity/aescan/assets/69896204/806c720d-54ad-46ee-a7a6-37a41fa21245)

2024-03-20 04:03 UTC, janmichek commented
> I got periodically 404 errors in FF, Chrome and Safari browsers.
> 
> Also I got these issues:
> 2024-03-18.5.19.30.mov
> 
> ![errr1](https://private-user-images.githubusercontent.com/69896204/313739093-a6d0c983-a16c-4274-9d01-2822785ea518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDYyMzMsIm5iZiI6MTcxMDkwNTkzMywicGF0aCI6Ii82OTg5NjIwNC8zMTM3MzkwOTMtYTZkMGM5ODMtYTE2Yy00Mjc0LTlkMDEtMjgyMjc4NWVhNTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOGQ1YTg1MDZlY2FkMjc2NThlYjg1ZTgzY2E5ZGM0Y2U0YWVkODM3MWM4NGZmYTNjMmQwNjI4MjA1ZjM1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QUWVX0HtO6d4zYJiCJWqpOXNLVuO78tO-Kiu_NGRxYg) ![cons](https://private-user-images.githubusercontent.com/69896204/313739176-806c720d-54ad-46ee-a7a6-37a41fa21245.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDYyMzMsIm5iZiI6MTcxMDkwNTkzMywicGF0aCI6Ii82OTg5NjIwNC8zMTM3MzkxNzYtODA2YzcyMGQtNTRhZC00NmVlLWE3YTYtMzdhNDFmYTIxMjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMjJkOTg2ZTAxNTMxNzlkYWQxYzlmZTRlZTE5MjNhY2ZiMDYwYjUxMDBhYTRiYzk5YWViMTRmODU4MmJmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1sjMW-adOFyyOFt1L1twDu9EsVvx4pgfP0KLU5iOAI)

I think it was caused by the deployment low resources. Can you retry now? However I am not sure how to test this, as wee need to have MDW in syncing state.

2024-03-20 11:09 UTC, Liubov-crypto commented
It was not working for me in the testnet. 
In mainnet I didn't get such issues as before. 
Probably you have a right, I have to catch somehow middleware out of sync to test it properly. I tried to change my network settings, but it seems to be different and it requires another approach.

2024-03-27 08:09 UTC, michele-franchi requested changes
I simulated it locally and looks good to me but I would change the wording a little bit.

2024-03-27 08:09 UTC, michele-franchi commented on src/components/TheHeader.vue
> +      The blockchain status is currently being synced. The data accuracy might be affected. Please check again
```suggestion
      Some services are currently being synced and data accuracy might be affected. Please check again
```

2024-03-28 06:30 UTC, janmichek commented on src/components/TheHeader.vue
> +      The blockchain status is currently being synced. The data accuracy might be affected. Please check again
Agree, changed

2024-03-28 09:32 UTC, michele-franchi approved these changes
Minor typo but looks good

2024-03-28 10:00 UTC, merged