feat: Improve UI and readability of panels in detail pages
aeternity/aescan pull request #717
Opened 2024-03-28 06:54 UTC by janmichek

## Description
Resolves #397

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-03-28 06:54 UTC, janmichek commented
@michele-franchi I kicked off the visual rework. It its still rough draft. Just wanted to sync with you on the idea before. Can you check the progress, please?

2024-05-05 22:41 UTC, michele-franchi reviewed
- Good to have the tooltips left aligned on tables
- I would go with the following structure for the hash and type:
<img width="1262" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/fd209d12-8db4-4fec-b569-585a97d63a83">
This simplifies the page and removes the ugly thing to have the hash at the right side (and type for transactions) when text is aligned to the left. This option is an alternative of what you proposed regarding hash and type:
<img width="458" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/e430bfc0-e8f2-4dc7-9479-b1b7642f3056">

Of course a similar behaviour applies for all the detail pages. For example with names the header would be "Name" instead of "Hash".

- I wouldn't remove bold from table headers, I would keep the current one for now. Can be improved in a second iteration

- All tables should be aligned in the same way in a details page, for example:

![image](https://github.com/aeternity/aescan/assets/11598532/9e50726b-7c76-4bd8-8c5c-9d98a3bad9f4)

2024-05-16 07:32 UTC, janmichek commented
Preview was rendered here:
https://pr-717-aescan.stg.service.aepps.com/

2024-05-16 07:49 UTC, janmichek commented on src/components/AppPanel.vue
> +      v-if="$slots.title"
Not related to issue. I renamed the slot names. Before was 'header' and 'heading'

2024-05-20 11:08 UTC, Liubov-crypto requested changes
1. Double appearing of account: 

![acc](https://github.com/aeternity/aescan/assets/69896204/9c2c2d08-0a3a-4612-971b-35bd05730991)

2. is alignment here correct? 

![micro](https://github.com/aeternity/aescan/assets/69896204/bff1443e-44ff-4d4a-9487-a82bd887c5ad)

2024-05-20 11:36 UTC, janmichek commented
> 1. Double appearing of account:
> 
> 
> ![acc](https://private-user-images.githubusercontent.com/69896204/332040580-9c2c2d08-0a3a-4612-971b-35bd05730991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDQ3MDcsIm5iZiI6MTcxNjIwNDQwNywicGF0aCI6Ii82OTg5NjIwNC8zMzIwNDA1ODAtOWMyYzJkMDgtMGEzYS00NjEyLTk3MWItMzViZDA1NzMwOTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDExMjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzYyNDlkZTMxYzY0ZDA0MGFjMTUwN2M5ZTZmNTBjYzJkYmQ5NjMyY2Q2MmJiYmE1Yjc3ZDMyNjVjNDFlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D7_AZynv0I1yG4icxExlI3FeHSA-MHoXSMYlu5VIHQM)
> 
>     2. is alignment here correct?
> 
> 
> ![micro](https://private-user-images.githubusercontent.com/69896204/332040807-bff1443e-44ff-4d4a-9487-a82bd887c5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDQ3MDcsIm5iZiI6MTcxNjIwNDQwNywicGF0aCI6Ii82OTg5NjIwNC8zMzIwNDA4MDctYmZmMTQ0M2UtNDRmZi00ZDRhLTk0ODctYTgyYmQ4ODdjNWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDExMjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNmM2ZTExOGRmNDY2OWY3MWUzZTk1YTFjMDJhYjI1YzlhNTg0ZjExYjUwZDk0NGZmZTllZWEyZjNhYzc4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rUEl1cVL9xvNbFMoEYejGre6F6gEiOv6J4RFLdjpnjk)

fixed

2024-05-20 13:31 UTC, Liubov-crypto approved these changes
lgtm

2024-05-29 07:46 UTC, michele-franchi requested changes
Really nice improvement. I would also change the following:
- Both AEX-9 and AEX-141 should be in the same row of the Smart Contract ID, for example:
<img width="1185" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/a410d76e-bbca-4e77-9804-5aed8afc3511">
- Mobile views should have a little bit more space, for example:
<img width="400" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/b4efa756-27d9-45fa-89df-76b0923b3fc8">

As you can see th and td have no space in between.

2024-05-29 11:20 UTC, michele-franchi requested changes
I think something went wrong with the develop merge in the "AENS Name" details page:

<img width="1297" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/52327474-222b-48b2-b1a4-30606100624f">

There are different labels. This happens in all names states: active, in auction and expired with different double labels.

2024-05-29 15:11 UTC, janmichek commented
> I think something went wrong with the develop merge in the "AENS Name" details page:
> <img alt="image" width="1297" src="https://private-user-images.githubusercontent.com/11598532/334777537-52327474-222b-48b2-b1a4-30606100624f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTU3NzEsIm5iZiI6MTcxNjk5NTQ3MSwicGF0aCI6Ii8xMTU5ODUzMi8zMzQ3Nzc1MzctNTIzMjc0NzQtMjIyYi00OGIyLWIxYTQtMzA2MDYxMDA2MjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDE1MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MWZmNGM2OGVlZGE0ZmMwMjJkNGU1MDhmYTBiZGE5N2YwMDY4NjYwNWYxZTkwNTJkM2I5ZjNmZjVkYmM5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5DkQXtIpZWGJBc54rH5d5AHLKKWjY33pxug5_dqzEh8">
> 
> There are different labels. This happens in all names states: active, in auction and expired with different double labels.

Fixed, probably some failed attempt of merging

2024-05-30 11:26 UTC, michele-franchi approved these changes
Let's fix the remaining things in the followup.

2024-05-30 11:29 UTC, merged