feat: Raw data pointer support for Ceres
aeternity/aescan pull request #761
Opened 2024-05-08 13:46 UTC by janmichek

## Description
resolves #733

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-14 14:08 UTC, Liubov-crypto requested changes
I got some issue when tried to check info about name that is in auction: 


https://github.com/aeternity/aescan/assets/69896204/afca465a-9ca7-4083-97ca-ef3d04657135



![au1](https://github.com/aeternity/aescan/assets/69896204/2b881d5c-658c-404d-86b3-f35badfe922f)

@janmichek  please check it

2024-05-15 11:04 UTC, janmichek commented
> I got some issue when tried to check info about name that is in auction:
> 2024-05-14.5.01.35.mov
> 
> ![au1](https://private-user-images.githubusercontent.com/69896204/330464205-2b881d5c-658c-404d-86b3-f35badfe922f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjM1NjgsIm5iZiI6MTcxNTc2MzI2OCwicGF0aCI6Ii82OTg5NjIwNC8zMzA0NjQyMDUtMmI4ODFkNWMtNjU4Yy00MDRkLTg2YjMtZjM1YmFkZmU5MjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA4NTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMDE4ZmIzNjAxYmZmYzIwMDg0YzI1OTczOGU0ZmJjZDg0Y2JkODVkOTBmNWY5YTM3OWNjZDZlOGI4MDIzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JC0EsKiY-Mp5a6faaPkIcqKSx_2yClZrWnhgrmSAcX4)
> 
> @janmichek please check it

Good catch, it's fixed now

2024-05-16 08:04 UTC, michele-franchi approved these changes
Looks good, just need to remove some console.log @janmichek.

2024-05-16 08:04 UTC, michele-franchi commented on src/utils/adapters.js
> +  console.log('formattedName', formattedName)
```suggestion
```

2024-05-16 08:04 UTC, michele-franchi commented on src/utils/adapters.js
> +  console.log('formattedName', formattedName)
```suggestion
```

2024-05-16 12:13 UTC, janmichek commented on src/utils/adapters.js
> +  console.log('formattedName', formattedName)
removed

2024-05-16 12:13 UTC, janmichek commented on src/utils/adapters.js
> +  console.log('formattedName', formattedName)
removed

2024-05-16 12:13 UTC, janmichek commented
@michele-franchi fixed, can you check again, please?

2024-05-17 08:04 UTC, michele-franchi approved these changes
LGTM

2024-05-17 08:04 UTC, merged