fix: Names in auction end date
aeternity/aescan pull request #799
Opened 2024-05-21 13:22 UTC by janmichek

## Description
fixes #794

## Demo
https://github.com/aeternity/aescan/assets/15363559/a7257043-6452-464e-8ee7-47f052888468

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] fix Names in auction end date

2024-05-22 10:16 UTC, Liubov-crypto commented
I'm still seeing meta.chain in auction and expired sections:  https://pr-799-aescan.stg.service.aepps.com/names/meta.chain

could you please check it @janmichek ?
https://github.com/aeternity/aescan/assets/69896204/ed455467-894a-40d8-b9cd-b9d2ec2e71a1

2024-05-22 17:50 UTC, janmichek commented
> > I'm still seeing meta.chain in auction and expired sections: https://pr-799-aescan.stg.service.aepps.com/names/meta.chain
> > could you please check it @janmichek ? https://github.com/aeternity/aescan/assets/69896204/ed455467-894a-40d8-b9cd-b9d2ec2e71a1
> 
> Hmm, interesting. The name appears in both lists. I will escalate this to MDW team. For now ignore it.

I created followup on our side to track the issue https://github.com/aeternity/aescan/issues/802

2024-05-28 11:44 UTC, michele-franchi requested changes
Looks good but the code can be slightly improved.

2024-05-28 11:44 UTC, michele-franchi commented on src/utils/format.js
> +    name.active
Shouldn't these be simple variables instead of functions?

2024-05-28 11:44 UTC, michele-franchi commented on src/components/NameDetailsPanel.vue
> +              :to="`/keyblocks/${ name.acutionEndsHeight || name.expirationHeight}`">
```suggestion
              :to="`/keyblocks/${name.acutionEndsHeight || name.expirationHeight}`">
```
Just an extra space

2024-05-29 08:40 UTC, michele-franchi approved these changes
Just an extra function but other than that looks good.

2024-05-29 08:40 UTC, michele-franchi commented on src/utils/format.js
> +  const isActive = () => name.active
```suggestion
  const isActive = name.active
```

2024-05-29 09:29 UTC, merged