feat: Names search case insensitive
aeternity/aescan pull request #824
Opened 2024-05-30 11:25 UTC by janmichek

## Description
resolves #817 

## Demo

![firefox_sTUua1fzTr](https://github.com/aeternity/aescan/assets/15363559/3907c62b-1882-4ccb-81c7-c85d027c5f01)

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [x] make search case insensitive

2024-05-30 14:23 UTC, Liubov-crypto approved these changes
LGTM

2024-06-03 07:38 UTC, michele-franchi requested changes
All the names have an "Expired" status in the search results page, because the "status" property is not present anymore.

2024-06-03 07:38 UTC, michele-franchi commented on src/components/SearchNamesTable.vue
> +        <td>{{ name.status ? 'Active' : 'Expired' }}</td>
Name status is missing

2024-06-03 08:37 UTC, janmichek commented on src/components/SearchNamesTable.vue
> +        <td>{{ name.status ? 'Active' : 'Expired' }}</td>
Right, fixed.

2024-06-03 08:38 UTC, janmichek commented on src/utils/format.js
> -export function formatNameStatus(name) {
I removed this logic as there is no way to determine whether the name is in auction or not. It was not even possible before.

2024-06-03 09:32 UTC, michele-franchi approved these changes
LGTM

2024-06-03 10:43 UTC, merged