feat: Ae coin details
aeternity/aescan pull request #827
Opened 2024-06-03 09:26 UTC by janmichek

## Description
resolves #749 

## Demo

https://github.com/aeternity/aescan/assets/15363559/85a209a8-387e-4055-a69b-8ed9f130b625

## Checklist:

- [x] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)

2024-06-03 14:58 UTC, Liubov-crypto requested changes
I think it's worth to check if text is placed in green filed when copy it: 
https://github.com/aeternity/aescan/assets/69896204/9f2a4278-1c3c-4adc-b270-097bed6d0ca1

Also for short names of tokens (the same on prod): 
https://github.com/aeternity/aescan/assets/69896204/92198165-f7fe-4bc5-9246-7725fa223800

2024-06-04 09:20 UTC, janmichek commented
> I think it's worth to check if text is placed in green filed when copy it:

Fixed


> Also for short names of tokens (the same on prod) and aligning is different from prod:

The layout is good. That's the thing we changed lately

2024-06-05 08:32 UTC, michele-franchi requested changes
I suggested some minor changes.

2024-06-05 08:32 UTC, michele-franchi commented on src/components/AeCoinPanel.vue
> +const priceChangeSign = computed(() => priceChange.value > 0 ? '+' : '')
```suggestion
const priceChangeSign = computed(() => priceChange.value > 0 ? '+' : '')
```

Shouldn't it be:
```
> 0: '+'
=0: ''
<0: '-'
```

2024-06-05 08:32 UTC, michele-franchi commented on src/utils/hints/aeCoinHints.js
> +  tokenSymbol: 'Reserved token name.',
```suggestion
  tokenSymbol: 'Reserved coin name.',
```

2024-06-05 08:32 UTC, michele-franchi commented on src/utils/hints/aeCoinHints.js
> +  price: 'Price of the token in AE and USD.',
```suggestion
  price: 'Price of the coin in AE and USD.',
```

2024-06-05 09:21 UTC, janmichek commented on src/components/AeCoinPanel.vue
> +const priceChangeSign = computed(() => priceChange.value > 0 ? '+' : '')
right, fixed

2024-06-05 10:45 UTC, merged