feat: Ae coin transactions
aeternity/aescan pull request #831
Opened 2024-06-04 08:39 UTC by janmichek

## Description
resolves #818 

## Demo

![image](https://github.com/aeternity/aescan/assets/15363559/cb2700f2-40a1-4c68-80ca-a21b4343997e)

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)

2024-06-04 08:54 UTC, janmichek commented
@michele-franchi one more implementation note.
To make things simple I just reused the transactions-panel which means that the 'type' column is shown.
I can still make it as proposed in initial requirements (without type column) but I would need to create dedicated components. Let me know what approach you like

2024-06-11 08:11 UTC, michele-franchi requested changes

2024-06-11 08:11 UTC, michele-franchi commented on src/utils/hints/aeCoinHints.js
> +  price: 'Price of the token in AE and USD.',
I would keep coin, instead of token.

2024-06-11 08:11 UTC, michele-franchi commented on src/utils/hints/aeCoinHints.js
>    totalSupply: 'Amount of tokens that will be mined.',
```suggestion
  totalSupply: 'Amount of coins in circulation.',
```

2024-06-11 08:11 UTC, michele-franchi commented on src/components/AeCoinTransactionsPanel.vue
> +import { isDesktop } from '~/utils/screen'
```suggestion
import { useTransactionsStore } from '@/stores/transactions'
import { isDesktop } from '@/utils/screen'
```

2024-06-11 08:29 UTC, janmichek commented on src/utils/hints/aeCoinHints.js
> +  price: 'Price of the token in AE and USD.',
all changed to 'coin'

2024-06-12 08:56 UTC, michele-franchi approved these changes

2024-06-12 09:03 UTC, merged