feat: AE coin markets
aeternity/aescan pull request #835
Opened 2024-06-06 14:39 UTC by janmichek

## Description
resolves #822 

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-12 14:16 UTC, janmichek commented on nuxt.config.ts
> +      '/proxy/gate': { proxy: 'https://api.gateio.ws/api/v4/spot/tickers?currency_pair=AE_USDT', cors: true },
Some of the request needed to be passed through proxy to get over CORS. Some links didn't need this approach

2024-06-13 10:37 UTC, Liubov-crypto requested changes
@janmichek  please check the description for 3 first column: 


https://github.com/aeternity/aescan/assets/69896204/4d02fb74-948c-465b-a65b-e3ae2dca2224

2024-06-13 11:03 UTC, janmichek commented
> @janmichek please check the description for 3 first column:
> 2024-06-13.1.33.59.mov

Thanks, fixed

2024-06-13 11:59 UTC, Liubov-crypto commented
LGTM

2024-06-17 08:20 UTC, michele-franchi requested changes

2024-06-17 08:20 UTC, michele-franchi commented on src/components/AeCoinMarketsTableCondensed.vue
> +            $ {{ formatNullable(formatNumber(coinStore?.coinW)) }}
```suggestion
            $ {{ formatNullable(formatNumber(coinW?.price)) }}
```

2024-06-17 08:20 UTC, michele-franchi commented on src/components/AeCoinMarketsTableCondensed.vue
> +            $ {{ formatNullable(formatNumber(coinStore?.coinW)) }}
```suggestion
            $ {{ formatNullable(formatNumber(coinW?.volume)) }}
```

2024-06-17 08:54 UTC, janmichek commented on src/components/AeCoinMarketsTableCondensed.vue
> +            $ {{ formatNullable(formatNumber(coinStore?.coinW)) }}
fixed

2024-07-15 14:15 UTC, merged