feat: DEX Trades General
aeternity/aescan pull request #875
Opened 2024-08-05 10:48 UTC by janmichek

## Description

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-05 12:39 UTC, janmichek commented
On hold, until this gets resolved https://github.com/aeternity/ae_mdw/pull/1882

2024-08-30 13:25 UTC, Liubov-crypto requested changes
I got some issues and new content isn't available: 

![err](https://github.com/user-attachments/assets/f3413ea0-9c43-4dd9-9ab5-fb85312217b1)

@janmichek  could you check it please?

2024-09-03 12:55 UTC, janmichek commented
> I got some issues and new content isn't available:
> 
> ![err](https://private-user-images.githubusercontent.com/69896204/363190422-f3413ea0-9c43-4dd9-9ab5-fb85312217b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjg0MDAsIm5iZiI6MTcyNTM2ODEwMCwicGF0aCI6Ii82OTg5NjIwNC8zNjMxOTA0MjItZjM0MTNlYTAtOWM0My00ZGQ5LTlhYjUtZmI4NTMxMjIxN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEyNTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNmM4YmYzZTExNDAzMWIxZDk4YTYzY2Q1YmUwY2NkZDEwMzFlYTI4MzQ5YjNkNjAxYjk5NDBmOTdhMDI2Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BR2lRqXn1c1K3oTLo2Ro6UQrDFgw3T3rN9pkECOemlY)
> 
> @janmichek could you check it please?
> 2024-08-30.4.21.46.mov

fixed

2024-09-04 14:56 UTC, Liubov-crypto approved these changes
LGTM

2024-09-13 12:07 UTC, merged