feat: Dex Trades per Token
aeternity/aescan pull request #876
Opened 2024-08-06 10:57 UTC by janmichek

## Description
resolves #522 

## Demo

## Checklist:

- [ ] I have read and followed the [Contributing Guide](../../CONTRIBUTING.md)  
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-07 08:18 UTC, janmichek commented
first https://github.com/aeternity/aescan/pull/875 needs to be merged as this PR is based on it

2024-11-21 12:39 UTC, janmichek commented on src/components/TimeToggleButton.vue
> +import { useUiStore } from '@/stores/ui'
not related to the feature, renamed confusing store name. App is too general

2024-11-21 12:51 UTC, janmichek commented on src/stores/dex.js
> +    const { data } = await axios.get(`${DEX_BACKEND_URL}/swap-routes/${tokenId}/${AE_TOKEN_ID}`)
dex changed link just today

2024-11-25 15:48 UTC, Liubov-crypto requested changes
In general LGTM. 

But I have a question regarding test tokens. For example if nobody was trading token there would be no trade activity. When I open Trades tab the page will be in endless loading: 
https://pr-876-aescan-testnet.stg.service.aepps.com/tokens/ct_25e9fYcVxp8qHhiHE3ZZKv1qsRZ8knvJefcUmTchZi33WANgt7?type=trades


https://github.com/user-attachments/assets/6749e26b-6422-42ad-9f2a-5855e4d9e044

![rem](https://github.com/user-attachments/assets/4eb0ffef-2739-4628-87e8-23e59b7839f9)

2024-12-10 12:31 UTC, janmichek commented
> In general LGTM.
> 
> But I have a question regarding test tokens. For example if nobody was trading token there would be no trade activity. When I open Trades tab the page will be in endless loading: https://pr-876-aescan-testnet.stg.service.aepps.com/tokens/ct_25e9fYcVxp8qHhiHE3ZZKv1qsRZ8knvJefcUmTchZi33WANgt7?type=trades
> 2024-11-25.5.36.51.mov
> 
> ![rem](https://private-user-images.githubusercontent.com/69896204/389600997-4eb0ffef-2739-4628-87e8-23e59b7839f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzQxNDMsIm5iZiI6MTczMzgzMzg0MywicGF0aCI6Ii82OTg5NjIwNC8zODk2MDA5OTctNGViMGZmZWYtMjczOS00NjI4LTg3ZTgtMjNlNTliNzgzOWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEyMzA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjE2ZmFjMWY1NzM2MDRmM2JkZjMzNzQ4NmNiYmEzODU2YmRjZWIzYjQ4MjJlODcwMWYxOTg1NjQ3MThkNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DCKLm9X1XLNCqqqrCXdIuQu06KvmWux4QbJSyaPXJ-g)

@Liubov-crypto good catch! Finally got it fixed.

2024-12-12 09:15 UTC, michele-franchi approved these changes
Looks good, just one http call seems can be optimised.

2024-12-12 09:18 UTC, michele-franchi requested changes
EDIT:
I just noticed that the button "Newer" seems to always be disabled? https://pr-876-aescan.stg.service.aepps.com/tokens/ct_2U1usf3A8ZNUcZLkZe5rEoBTxk7eJvk9fcbRDNqmRiwXCHAYN?type=trades

https://github.com/user-attachments/assets/5e6213f4-8916-4610-9d81-bbcf18fd1f72

2024-12-13 14:27 UTC, janmichek commented
> EDIT: I just noticed that the button "Newer" seems to always be disabled? https://pr-876-aescan.stg.service.aepps.com/tokens/ct_2U1usf3A8ZNUcZLkZe5rEoBTxk7eJvk9fcbRDNqmRiwXCHAYN?type=trades
> dex-trades.mov

Good catch, ser. There was FE wrong implementation + its a blocking MDW issue.

2025-01-13 08:29 UTC, merged